### ISSUE TITLE
App crashes upon open on Android 6 & 7

### ISSUE THREAD

**Issue by BostonZcash** [nighthawk-apps/nighthawk-wallet-android#1]
User reports that opening the app (v1.0.0) results in an immediate crash on Android 7.1.1 (Nougat).

He further reports he needs 'at least `24` for the `minSdkVersion`' here:

https://github.com/nighthawk-apps/nighthawk-wallet-android/blob/master/buildSrc/src/main/java/com/nighthawkapps/wallet/android/Dependencies.kt#L10-L11

User submitted crash report through Android.

**To-do:**
- Investigate crash report if received
- Test against lower versions of Android

**Comment by BostonZcash** [comment]
Received a second report of crashing on Android 7, as well as one on Android 6.

For Android 6, user mentioned choosing 'New' after app start resulted in an immediate crash and the system warning: 'Unfortunately, Nighthawk has stopped'.

**Comment by BostonZcash** [comment]
Adi able to reproduce. It's due to the missing Java crypt library on older Android releases.

**Comment by nighthawk24** [comment]
Android Phones without Google Play Services do not have security libs that were added since Android 8
java.security.NoSuchAlgorithmException: SecretKeyFactory PBKDF2WithHmacSHA512 implementation not found

The only "fix" for now is to support phones running Android 8.0 Oreo and above.
