### ISSUE TITLE
chore: update SideShift dialogue box copy

### ISSUE THREAD

**Issue by BostonZcash** [nighthawk-apps/nighthawk-wallet-android#10]
Current copy:

> Your Z-Address has been copied to the clipboard.
> 
> Select "Open Browser" below and paste your address into the SideShift Page and select Shielded Zcash as the receiving address

Suggested copy:

> Your Z-address has been copied to the clipboard.
> 
> Choose 'Open Browser' below, select 'Zcash (Shielded)' as the receiving coin on the SideShift page, and then paste your Z-address.

**Comment by nighthawk24** [comment]
Fixes in https://github.com/nighthawk-apps/nighthawk-wallet-android/pull/12
