### ISSUE TITLE
Initial wallet scan never completes with Rust error

### ISSUE THREAD

**Issue by sethforprivacy** [nighthawk-apps/nighthawk-wallet-android#118]
**Bug vs expected behavior**
Expected the wallet to sync normally, but it didn't even error out initially, it just never showed sent funds. Upon inspecting it finally threw an error and cannot complete sync.

**Device (please complete the following information):**
 - Android Device: Pixel 6
 - Android Version 12

**To Reproduce**
1. Create a new wallet
2. Wallet never syncs
3. Do "full restore"
4. Wallet now complains it cannot sync

**Screenshots**
![image](https://user-images.githubusercontent.com/40500387/172267530-f809aa9f-cd9c-408b-8f07-21eb72a40d05.png)

**Comment by sethforprivacy** [comment]
Quick note, the wallet appears to get through the download stage but never completes the scanning phase.

I also noticed Zecwallet Lite is also not syncing for me -- is there some bug or network issue after NU5?

**Comment by sethforprivacy** [comment]
The update to Zecwallet Lite today resolved the similar issue for that wallet and funds now show there properly, FWIW.

**Comment by nighthawk24** [comment]
> The update to Zecwallet Lite today resolved the similar issue for that wallet and funds now show there properly, FWIW.

The ZecWallet issue might not be related as it uses a custom lightwalletd backend.

**Comment by sethforprivacy** [comment]
Rescan with wipe just says no funds available now and never seems to try to sync after showing "downloading 100%" for a couple of seconds.

I even tried restoring from seed fresh and it still never seems to sync (though it shows no error or sync progress at all).

**Comment by sethforprivacy** [comment]
The balance screen shows that the wallet is clearly stuck at block 1681500 and never gets past that, but for some reason the wallet appears to think it's properly synced.
