### ISSUE TITLE
NonFree lib in F-Droid build

### ISSUE THREAD

**Issue by linsui** [nighthawk-apps/nighthawk-wallet-android#127]
com.google.android.gms:play-services-oss-licenses is not FOSS. See https://maven.google.com/com/google/android/gms/play-services-oss-licenses/12.0.0/play-services-oss-licenses-12.0.0.pom. Could you please replace with an FOSS alternative (see https://gitlab.com/-/snippets/1896503)? Thanks!

**Comment by nighthawk24** [comment]
Thanks for point it out! We will have this resolved in the next version v2.0.03
