### ISSUE TITLE
Birthday height defaults to 930000

### ISSUE THREAD

**Issue by madars** [nighthawk-apps/nighthawk-wallet-android#17]
**Bug vs expected behavior**
I'm trying to restore a ZIP-32 seed and am entering a birthday height that's past 1080000. NHW ignores this height defaults to rescanning all blocks since 930000.

**Device (please complete the following information):**
 - Android Device: Pixel 4a
 - Android Version: 11

**To Reproduce**
1. Launch Nighthawk Wallet, choose to restore a wallet, enter your seed, enter a birthday height of 1080309.
2. Observe that the wallet is downloading a lot of blocks.
3. Go to settings, backup wallet, view seed, and see birthday height of 930 000.

**Comment by nighthawk24** [comment]
I believe this was fixed a couple versions ago!
