### ISSUE TITLE
New wallet birthday hardcoded to block 1,290,000

### ISSUE THREAD

**Issue by bobanm** [nighthawk-apps/nighthawk-wallet-android#76]
**Bug vs expected behavior**

This could be a regression of issue #17

I created a wallet a few days ago. The app showed block 1,290,000 as the wallet birthday block, even though at that time the latest block was 1,345,221.

Could this be related to the issue #20, where the slow initial sync could be attributed to the app trying to sync way too many blocks headers than necessary? In my case, the initial sync was indeed too slow. I'd say it took about 10 minutes or even longer.

Is that what wallet birthday is used for -- to know how many block in the past to sync when restoring a wallet?

**Nighthawk version**
1.0.22

**Device**
- Android Device: OnePlus 3
- Android Version 9

**To Reproduce**
1. Install app
1. Create new wallet

**Comment by nighthawk24** [comment]
The wallet relies on hardcoded checkpoints to sync from.
Checkpoint updated to 1,300,000 in #83
