### ISSUE TITLE
Insufficient funds message shown when there were sufficient funds for the transaction and transaction was successfully sent

### ISSUE THREAD

**Issue by bobanm** [nighthawk-apps/nighthawk-wallet-android#78]
**Bug vs expected behavior**

The error message "Oops! Failed to send due to insufficient funds!" pops out when sending ZEC. Not sure what triggered the message, as there were sufficient funds and I could see the transaction in the mempool immediately after. So I didn't even have to retry the transaction. This happened at least twice.

**Nighthawk version**
1.0.23

**Device**
- Android Device: OnePlus 3
- Android Version 9

**To Reproduce**
1. Go to "Send Zcash"
1. Complete the form with amount that is lower than your balance
1. Tap on Send

**Comment by nighthawk24** [comment]
Thank you for reporting this!

**Comment by nighthawk24** [comment]
Fixed #83
