### ISSUE TITLE
Simplify UX by not mentioning "available" funds on home view and balance view

### ISSUE THREAD

**Issue by bobanm** [nighthawk-apps/nighthawk-wallet-android#81]
**Is your feature request related to a problem? Please describe.**

This is loosely related to #79, where dropping the requirement for 8 block confirmations would make funds available much faster and remove the need to differentiate between available and unavailable funds.

The only moment when a user should be informed that there is a difference between available and pending funds is on the send view, when they are making a new transaction.

Most of the time, users don't spend funds immediately after receiving. For them all the funds will be available all the time. Not being confused with what "available funds" really means will be a nice UX improvement.

**Describe the solution you'd like**

1. Instead of using the word "available" consider using "spendable". I think it is more descriptive to the users.
2. Home view and balance view should show total funds, including any pending transaction.
3. Send view should be the only one to differentiate between **total funds** and **spendable funds**.

**Comment by nighthawk24** [comment]
Thanks @bobanm, your feedback will be shared with our UX designer who will be starting the Design Sprint in October, after the NU5 integration.

**Comment by nighthawk24** [comment]
Nighthawk v2 now shows Total, Available & Transparent Balances.
