### ISSUE TITLE
Send Flow shows error message while sending funds.

### ISSUE THREAD

**Issue by nighthawk24** [nighthawk-apps/nighthawk-wallet-android#82]
**To Reproduce**
1. Send Funds
2. See incorrect message of "Oops! Failed to send due to insufficient funds!"
3. User is stuck on the send screen with animation when the funds are actually sent out.

**Comment by bobanm** [comment]
This is the same issue as the one I reported in #78, right?

**Comment by nighthawk24** [comment]
Dupe of #78
